### ISSUE TITLE
useradd / adduser are not working on botbrew-basil

### ISSUE THREAD

**Issue by davidhalter** [jyio/botbrew-gui#20]
Hey!
Thank you for your great software, I really waited a long time for a good package manager on Android.

Apt-get (and for me aptitude) are working great. I installed already > 100 packages! (I even compiled the bb demo)

But there's a little drawback that I cannot fix.
When installing openssh-client, ssh wants to create a new user ('ssh'):

```
# adduser ssh 
Adding user `ssh' ...
Adding new group `ssh' ...
adduser: /usr/sbin/groupadd -g 102 ssh' returned error code 1. Exiting.
```

The same thing happens when you try to use `adduser` from the CLI.
Oddly enough `useradd` seem to work neither (fails without output but with error code 1), but /etc/passwd as well as /etc/shadow and /etc/group are editable (and there are no lock files). 

Have you any ideas, what might be the problem?
David

**Comment by jyio** [comment]
Hey David, thanks for bringing this to my attention. I was able to reproduce this problem on a freshly-bootstrapped instance of BotBrew. Here's the relevant [strace dump](http://pastebin.com/TPca5rPT), and this is the problem:

```
open("/etc/login.defs", O_RDONLY)       = -1 ENOENT (No such file or directory)
```

Normally, Debian comes with an essential package `login` that installs `login.defs`. `openssh-client` does not declare this dependency because essential packages are assumed to be installed already as part of the base system. BotBrew does not install anything by default, in the interest of saving resources, resulting in this problem. How should we deal with this issue?
- recommend that people install `botbrew-debian-minimal` (but: most users probably don't need many of the essential packages)
- provide another metapackage that depends on some useful essential packages, such as `login` and `findutils` (but: we'd be making assumptions about what people want)
- maintain a list of essential packages necessary for each bit of software (but: people would have to manually look up the solution when they run into issues)

Meanwhile, this should get you back on track:

```
apt-get install login
dpkg --configure -a
```

**Comment by davidhalter** [comment]
This fixes my problem, thank you! 

I think it is important, that users don't have to deal with the question, wheter or not they have to install another package for openssh-client.  Because actually that is exactly what a package manager does: Resolve those dependencies.

IMHO I think disk space is not too much of a problem. The default debian packages are not that big (Most tables/phones are shipped with 16/32 GB disks, where a few MB just don't matter). Clearly there needs to be a way for users to save ressources, but I think this should not be the default case. I would cleary recommmend that people install this package (or even installl it at the beginning).
Typically botbrew is for people, which seriously search an "open" operating system. I don't think they care too much about a little bit of space.

Maybe it's even an option to install `botbrew-debian-minimal` by default. Maybe you'd consider switching from `apt-get` to `aptitude`? In this case you would have proper removals of packages (and the dependencies). However, this has also drawbacks (ressources). And I don't think it is too important, because
botbrew-basil is pretty awesome already.

BTW: I think there's some messup with the gpg keys. I don't know what's the problem exactly, but I have to confirm many packages, because they are untrusted. I don't think this would be hard to fix, it's probably just something in the /etc/apt/trusted.gpg.
