### ISSUE TITLE
Availability of repository source?

### ISSUE THREAD

**Issue by nwf** [jyio/botbrew-gui#23]
Hallo!  Forgive me if this is the wrong place to ask, but is the source behind http://repo.botbrew.com/basil/ available?  I've not been able to find it (though that may say more about me than about its availability ;) ).  https://github.com/jyio/botbrew seems to describe exclusively the old opkg-based system, yes?

Thanks!

**Comment by jyio** [comment]
They are actually the same as the opkg packages, just batch-converted to debs. So I expect many of them to fail; but I did manually tweak a couple to make sure they work, and these are in _basil_'s main repository. That toolchain is being ported to _basil_, and it would probably be possible to do self-hosted builds on the Android device itself (because the NDK builds cleanly on/for ARM).

So... yeah, it's available, and you found it :)
